#การดำเนินการทางคณิตศาสตร์
A = input("first value\t")
B = input("second value\t")
A = int(A)
B = int(B)
print("ผลบวก\t" , A+B)
print("ผลลบ\t" , A-B)
print("ผลคูณ\t" , A*B)
print("ผลหาร\t" , A/B)
print("ผลหารปัดเศษ\t" , A//B)
print("ผลหารเอาเศษ\t" , A%B)
print("ยกกำลัง\t" , A**B)